---
- name: Install AWS CloudWatch Agent
  block:
    - name: Install xz-utils (required when using deb parameter of apt module)
      package:
        name:
          - xz-utils
    - name: Download the AWS CloudWatch Agent Debian package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb
    - name: Install AWS CloudWatch Agent Debian package
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - cloudwatch-agent
- name: Install AWS CloudWatch Agent
  block:
    - name: Install AWS CloudWatch Agent RPM
      dnf:
        name:
          - https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - cloudwatch-agent
# The AWS CloudWatch Agent systemd unit kicks off a process that
# starts the CloudWatch Agent and then dies.  Therefore we can't start
# it here because it will be started again during the idempotence test
# and therefore will fail idempotence.
- name: Enable AWS CloudWatch Agent
  service:
    name: amazon-cloudwatch-agent
    enabled: yes
  tags:
    - cloudwatch-agent
