---
- name: Install AWS CloudWatch Agent (Debian)
  block:
    - name: Install xz-utils (required when using deb parameter of apt module)
      package:
        name:
          - xz-utils
    - name: Download the AWS CloudWatch Agent Debian package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb
    - name: Install AWS CloudWatch Agent Debian package
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - cloudwatch-agent
- name: Install AWS CloudWatch Agent (RedHat)
  block:
    - name: Install AWS CloudWatch Agent RPM
      dnf:
        name:
          - https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - cloudwatch-agent
- name: Copy over generic CloudWatch Agent configuration, if necessary
  block:
    - name: Check if a CloudWatch Agent configuration already exists
      stat:
        path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      register: agent_config
    - name: Copy over generic CloudWatch Agent configuration, if necessary
      copy:
        src: amazon-cloudwatch-agent.json
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        mode: 0600
      when: not agent_config.stat.exists
  tags:
    - cloudwatch-agent
- name: Add Debian-specific sections to CloudWatch Agent configuration
  block:
    - name: Check if CloudWatch Agent configuration already has a section for syslog
      json_patch:
        src: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        operations:
          - op: test
            path: "/logs/logs_collected/files/collect_list/*/file_path"
            value: /var/log/syslog
      register: syslog_check
    - name: Add CloudWatch Agent configuration for syslog, if necessary
      json_patch:
        src: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        operations:
          - op: add
            path: "/logs/logs_collected/files/collect_list/-"
            value:
              file_path: /var/log/syslog
              log_group_name: /instance-logs/syslog
              log_stream_name: {instance_id}
      when: not syslog_check.tested
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - cloudwatch-agent
# The AWS CloudWatch Agent systemd unit kicks off a process that
# starts the CloudWatch Agent and then dies.  Therefore we can't start
# it here because it will be started again during the idempotence test
# and therefore will fail idempotence.
- name: Enable AWS CloudWatch Agent
  service:
    name: amazon-cloudwatch-agent
    enabled: yes
  tags:
    - cloudwatch-agent
